### ISSUE TITLE
Inverse laplace 

### ISSUE THREAD

**Issue by ritwikraha** [ritwikraha/Control-Theory-Lab-IC--491-#1]
Inverse Laplace of transfer function object could not be found.
no formal way to convert a transfer function object to a matrix.
![image](https://user-images.githubusercontent.com/44690292/48972233-65267500-f04c-11e8-98bb-c98cb40ac83f.png)

**Comment by ayulockin** [comment]
You must have named a .m file with the name of the function. That's why this is coming

**Comment by ayulockin** [comment]
installing matlab. expired previous one. doing all over again:(

**Comment by ayulockin** [comment]
https://www.mathworks.com/matlabcentral/answers/373431-trouble-with-inverse-laplace-operation
have a look:  the Control System Toolbox and Symbolic Math Toolbox do not have any way of communicating with each other without intervention.
